stages:
  - test
  - deploy

test:
  stage: test
  image: thomasWeise/texlive
  script:
  - cd src
  - mkdir deploy
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory deploy main.tex
  tags:
  - docker

install: true

before_deploy:
  - sudo add-apt-repository --yes ppa:coolwanglu/pdf2htmlex
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends --yes pdf2htmlex
  - cd deploy
  - rm *.log *.aux
  - pdf2htmlEX --embed cfijo --printing 0 --optimize-text 1 --fit-width 1200 main.pdf
  - mv main.html demostraciones.html
  - mv main.pdf demostraciones.pdf
  - cp ../../index.html index.html

deploy:
  stage: deploy
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: src/deploy
  on:
    branch: master
  target_branch: gh-pages
