before_install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-full
- cd src
- mkdir deploy

script:
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory deploy main.tex

before_deploy:
- sudo add-apt-repository --yes ppa:coolwanglu/pdf2htmlex
- sudo apt-get update
- sudo apt-get install --no-install-recommends --yes pdf2htmlex
- cd deploy
- rm *.log *.aux
- for i in *.pdf; do mkdir ${i%%.*}; pdf2htmlEX --embed cfijo --printing 0 --optimize-text 1 --dest-dir ${i%%.*} --fit-width 1200 $i; done
- for i in *.pdf; do title=$(grep -E "\\title ?{(.+)}" ../${i%%.*}.tex | sed -r 's|\\title ?\{(.+)\}|\1|g'); sed "s|PDF_FILENAME|$i|g" ../../templateLine.html | sed "s|HTML_FILENAME|${i%%.*}/${i%%.*}.html|g" |sed "s|TITLE|$title|g" >> lines.html; done
- sed "s|TEMPLATE_LINES|$(<lines.html)|g" ../../template.html > index.html
- rm lines.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: src/deploy
  on:
    branch: master
  target_branch: gh-pages
